volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: nvdrmv/foodgram_backend
    volumes:
      - static:/backend_static/
      - media:/media/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    container_name: foodgram-front
    image: nvdrmv/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
