# Generated by Django 3.2 on 2024-10-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241010_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite_count',
        ),
    ]
