# Generated by Django 3.2 on 2024-10-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241008_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortenedurl',
            options={'verbose_name': 'короткая ссылка', 'verbose_name_plural': 'короткие ссылки'},
        ),
    ]
