# Generated by Django 3.2 on 2024-10-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_favorite_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
