# Generated by Django 3.2 on 2024-10-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'favorites', 'ordering': ('user',), 'verbose_name': 'избранное', 'verbose_name_plural': 'избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'default_related_name': 'recipe_ingredients', 'ordering': ('recipe',), 'verbose_name': 'Ингредиент для рецепта', 'verbose_name_plural': 'Ингредиенты для рецепта'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_carts', 'ordering': ('user',), 'verbose_name': 'список покупок', 'verbose_name_plural': 'рецепты в списке покупок'},
        ),
        migrations.AlterModelOptions(
            name='shortenedurl',
            options={'verbose_name': 'короткая ссылка', 'verbose_name_plural': 'короткие ссылки'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('follower',), 'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
