# Generated by Django 3.2 on 2024-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20241008_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='Количество добавлений рецепта в избранное'),
        ),
    ]
